WebApplication1/Controllers/GioHangController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class GioHangController : Controller
    {
        // GET: GioHang
        public ActionResult Index()
        {
            string MaTaiKhoan = User.Identity.GetUserId();
            return View(GioHangBus.DanhSach(MaTaiKhoan));
        }
        [HttpPost]
        public ActionResult Them(int MaSanPham)
        {
            GioHangBus.Them(MaSanPham, User.Identity.GetUserId());
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult CapNhat(int SoLuong,int MaSanPham)
        {
            GioHangBus.CapNhat(SoLuong,MaSanPham,User.Identity.GetUserId());
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;
using WebApplication1.Models.ViewModel;

namespace WebApplication1.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products

        public ActionResult Index(int Page = 1)
        {
            var DsSanPham = SanPhamBus.PageDanhSach(Page, 8);
            return View(DsSanPham);
        }

        // GET: SanPham/Details/5
        public ActionResult Details(int id)
        {
            var BinhLuan = BinhLuanBUS.DanhSach(id);
            var ChiTietSP = SanPhamBus.ChiTiet(id);
            var ChiTietLoaiSP = LoaiBus.ChiTietViewModel(ChiTietSP.MaLoai);
            var ChitTietHangSP = HangBus.ChiTietViewModel(ChiTietSP.MaLoai);
            return View(new SanPhamViewModel() {LoaiSP=ChiTietLoaiSP,HangSP=ChitTietHangSP,SanPham=ChiTietSP,BinhLuanSP=BinhLuan });
        }
       
    }
}

WebApplication1/Views/GioHang/Index.cshtml
@model IEnumerable<MobileShopConnection.v_GioHang>
@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    bool check = Model.Any();
}

<div class="site-branding-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="logo">
                    <h1><a href="./"><img src="~/ShopOnline/img/logo.png"></a></h1>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="shopping-item">
                    <a href="@Url.Action("Cart", "Home")">Cart - <span class="cart-amunt">$800</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">5</span></a>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End site branding area -->

<div class="mainmenu-area">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li><a href="@Url.Action("Index", "Product")">Shop page</a></li>
                    <li class="active"><a href="@Url.Action("Cart", "Home")">Cart</a></li>
                    <li><a href="@Url.Action("Checkout", "Home")">Checkout</a></li>
                    <li><a href="#">Category</a></li>
                    <li><a href="#">Others</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
</div> <!-- End mainmenu area -->

<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Shopping Cart</h2>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End Page title area -->


<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="single-sidebar">
                    <h2 class="sidebar-title">Search Products</h2>
                    <form action="#">
                        <input type="text" placeholder="Search products...">
                        <input type="submit" value="Search">
                    </form>
                </div>

                <div class="single-sidebar">
                    <h2 class="sidebar-title">Products</h2>
                    <div class="thubmnail-recent">
                        <img src="~/ShopOnline/img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="#">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$800.00</del>
                        </div>
                    </div>
                    <div class="thubmnail-recent">
                        <img src="~/ShopOnline/img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="#">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$800.00</del>
                        </div>
                    </div>
                    <div class="thubmnail-recent">
                        <img src="~/ShopOnline/img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="#">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$800.00</del>
                        </div>
                    </div>
                    <div class="thubmnail-recent">
                        <img src="~/ShopOnline/img/product-thumb-1.jpg" class="recent-thumb" alt="">
                        <h2><a href="#">Sony Smart TV - 2015</a></h2>
                        <div class="product-sidebar-price">
                            <ins>$700.00</ins> <del>$800.00</del>
                        </div>
                    </div>
                </div>

                <div class="single-sidebar">
                    <h2 class="sidebar-title">Recent Posts</h2>
                    <ul>
                        <li><a href="#">Sony Smart TV - 2015</a></li>
                        <li><a href="#">Sony Smart TV - 2015</a></li>
                        <li><a href="#">Sony Smart TV - 2015</a></li>
                        <li><a href="#">Sony Smart TV - 2015</a></li>
                        <li><a href="#">Sony Smart TV - 2015</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-9">
                <div class="product-content-right">
                    <div class="woocommerce">
                        @if (check == true)
                        {
                            using (Html.BeginForm("CapNhat", "GioHang", FormMethod.Post))
                            {
                                <table cellspacing="0" class="shop_table cart">
                                    <thead>
                                        <tr>
                                            <th class="product-remove">&nbsp;</th>
                                            <th class="product-thumbnail">&nbsp;</th>
                                            <th class="product-name">Product</th>
                                            <th class="product-price">Price</th>
                                            <th class="product-quantity">Quantity</th>
                                            <th class="product-subtotal">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {

                                            <tr class="cart_item">
                                                <td class="product-remove">
                                                    <a title="Remove this item" class="remove" href="#">×</a>
                                                </td>

                                                <td class="product-thumbnail">
                                                    <a href="#"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="~/ShopOnline/img/@item.HinhAnh"></a>
                                                </td>

                                                <td class="product-name">
                                                    <a href="@Url.Action("Details", "Products", new { id = item.MaSanPham })">@item.TenSP</a>
                                                </td>

                                                <td class="product-price">
                                                    <span class="amount">@string.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:c}", item.GiaBan)</span>
                                                </td>
                                                
                                                <td class="product-quantity">
                                                    <div class="quantity buttons_added">
                                                        @Html.Hidden("MaSanPham", item.MaSanPham)
                                                        <input type="button" class="minus" value="-">
                                                        <input type="number" name="SoLuong" size="4" class="input-text qty text" title="Qty" value="@item.SoLuong" min="0" step="1">
                                                        <input type="button" class="plus" value="+">
                                                    </div>
                                                </td>
                                                <td class="product-subtotal">
                                                    <span class="amount">@string.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:c}", item.ThanhTien)</span>
                                                </td>

                                                
                                            </tr>
                                        }
                                        <tr>
                                            <td class="actions" colspan="6">
                                                <input type="submit" value="Cập nhật giỏ hàng" name="update_cart" class="button">
                                                <input type="submit" value="Checkout" name="proceed" class="checkout-button button alt wc-forward">
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            }
                        }
                        else
                        {
                            <h3>Bạn Chưa Có Sản Phẩm Nào Trong Giỏ Hàng</h3>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="footer-top-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="footer-about-us">
                    <h2>u<span>Stora</span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                    <div class="footer-social">
                        <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">User Navigation </h2>
                    <ul>
                        <li><a href="#">My account</a></li>
                        <li><a href="#">Order history</a></li>
                        <li><a href="#">Wishlist</a></li>
                        <li><a href="#">Vendor contact</a></li>
                        <li><a href="#">Front page</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">Categories</h2>
                    <ul>
                        <li><a href="#">Mobile Phone</a></li>
                        <li><a href="#">Home accesseries</a></li>
                        <li><a href="#">LED TV</a></li>
                        <li><a href="#">Computer</a></li>
                        <li><a href="#">Gadets</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-sm-6">
                <div class="footer-newsletter">
                    <h2 class="footer-wid-title">Newsletter</h2>
                    <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                    <div class="newsletter-form">
                        <form action="#">
                            <input type="email" placeholder="Type your email">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End footer top area -->

<div class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="copyright">
                    <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="footer-card-icon">
                    <i class="fa fa-cc-discover"></i>
                    <i class="fa fa-cc-mastercard"></i>
                    <i class="fa fa-cc-paypal"></i>
                    <i class="fa fa-cc-visa"></i>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End footer bottom area -->
<!-- Latest jQuery form server -->
<script src="https://code.jquery.com/jquery.min.js"></script>

<!-- Bootstrap JS form CDN -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<!-- jQuery sticky menu -->
<script src="~/ShopOnline/js/owl.carousel.min.js"></script>
<script src="~/ShopOnline/js/jquery.sticky.js"></script>

<!-- jQuery easing -->
<script src="~/ShopOnline/js/jquery.easing.1.3.min.js"></script>

<!-- Main Script -->
<script src="~/ShopOnline/js/main.js"></script>