WebApplication1/Areas/Admin/Controllers/LoaiSPController.cs
using MobileShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LoaiSPController : Controller
    {
        
        // GET: Admin/LoaiSP
        public ActionResult Index(int Page = 1)
        {
            var DsLoaiSP = LoaiBus.PageDanhSach(Page,10);
            return View(DsLoaiSP);
        }

        // GET: Admin/LoaiSP/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSP/Create
        public ActionResult Create()
        {
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            return View();
        }

        // POST: Admin/LoaiSP/Create
        [HttpPost]
        public ActionResult Create(LoaiSP LoaiSP)
        {
            try
            {
                // TODO: Add insert logic here
                LoaiBus.Them(LoaiSP);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSP/Edit/5
        public ActionResult Edit(int id)
        {
            var rs = LoaiBus.ChiTiet(id);
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            return View(rs);
        }

        // POST: Admin/LoaiSP/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, LoaiSP LoaiSP)
        {
            try
            {
                // TODO: Add update logic here
                LoaiBus.Sua(LoaiSP);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSP/Delete/5
        public ActionResult Delete(int id)
        {
            var rs = LoaiBus.ChiTiet(id);
            return View(rs);
        }

        // POST: Admin/LoaiSP/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                LoaiBus.Xoa(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Deleted(int Page = 1)
        {
            var rs = LoaiBus.PageDanhSachDaXoa(Page,10);
            return View(rs);
        }
        public ActionResult Restore(int id)
        {
            LoaiBus.KhoiPhuc(id);
            return RedirectToAction("Deleted");
        }
    }
}

WebApplication1/Areas/Admin/Controllers/SanPhamController.cs
using MobileShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SanPhamController : Controller
    {
        // GET: Admin/SanPham
        public ActionResult Index(int Page = 1)
        {
            var DsSanPham = SanPhamBus.PageDanhSach(Page, 10);
            return View(DsSanPham);
        }

        // GET: Admin/SanPham/Details/5
        public ActionResult Details(int id)
        {
            var ChiTiet = SanPhamBus.ChiTiet(id);
            return View(ChiTiet);
        }

        public ActionResult Deleted(int Page = 1)
        {
            var DsSanPham = SanPhamBus.PageDanhSachDaXoa(Page, 10);
            return View(DsSanPham);
        }

        public ActionResult Restore(int id)
        {
            SanPhamBus.KhoiPhuc(id);
            return RedirectToAction("Deleted");
        }

        // GET: Admin/SanPham/Create
        public ActionResult Create()
        {
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            List<CustomDropDownList> TinhTrang = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Còn Hàng",Value=1 },
                new CustomDropDownList {Text="Hết Hàng",Value=0 }
            };
            ViewBag.TinhTrang = new SelectList(TinhTrang, "Value", "Text");
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            ViewBag.MaHang = new SelectList(HangBus.DanhSach(), "MaHang", "TenHang");
            ViewBag.MaLoai = new SelectList(LoaiBus.DanhSach(), "MaLoai", "TenLoai");
            return View();
        }

        // POST: Admin/SanPham/Create
        [HttpPost]
        public ActionResult Create(SanPham sp)
        {
            if (HttpContext.Request.Files.Count > 0)
            {
                var hpf = HttpContext.Request.Files[0];
                if (hpf.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    string fullPathWithFileName = "/ShopOnline/img/" + fileName + ".jpg";
                    hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                    sp.HinhAnh = fileName + ".jpg";
                }
            }
            SanPhamBus.Them(sp);
            return RedirectToAction("Index");
        }

        // GET: Admin/SanPham/Edit/5
        public ActionResult Edit(int id)
        {
            var rs = SanPhamBus.ChiTiet(id);
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            List<CustomDropDownList> TinhTrang = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Còn Hàng",Value=1 },
                new CustomDropDownList {Text="Hết Hàng",Value=0 }
            };
            ViewBag.TinhTrang = new SelectList(TinhTrang, "Value", "Text");
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            ViewBag.MaHang = new SelectList(HangBus.DanhSach(), "MaHang", "TenHang",rs.MaHang);
            ViewBag.MaLoai = new SelectList(LoaiBus.DanhSach(), "MaLoai", "TenLoai",rs.MaLoai);
            return View(rs);
        }

        // POST: Admin/SanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, SanPham sp)
        {
            var db = new MobileShopConnectionDB();
            var rs = db.SingleOrDefault<MobileShopConnection.SanPham>("select HinhAnh from sanpham where MaSP=@0", id);
            if (HttpContext.Request.Files.Count > 0)
            {
                var hpf = HttpContext.Request.Files[0];
                if (hpf.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    string fullPathWithFileName = "/ShopOnline/img/" + fileName + ".jpg";
                    hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                    sp.HinhAnh = fileName + ".jpg";

                }
                else
                {
                    sp.HinhAnh = rs.HinhAnh;
                }
            }
            SanPhamBus.Sua(sp);
            return RedirectToAction("Index");
        }

        // GET: Admin/SanPham/Delete/5
        public ActionResult Delete(int id)
        {
            var rs = SanPhamBus.ChiTiet(id);
            return View(rs);
        }

        // POST: Admin/SanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                SanPhamBus.Xoa(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Areas/Admin/Views/LoaiSP/Create.cshtml
@model MobileShopConnection.LoaiSP

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminMainLayout.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Thêm Loại Sản Phẩm
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="@Url.Action("Index","LoaiSP")">Loại Sản Phẩm</a>
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> Thêm Loại Sản Phẩm
                </li>
            </ol>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>LoaiSP</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    

                    <div class="form-group">
                        <label class="control-label col-md-2">Tên Loại</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Bị Xóa</label>
                        <div class="col-md-10">
                            @Html.DropDownList("BiXoa", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.BiXoa, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <!-- /.row -->
</div>

WebApplication1/Areas/Admin/Views/LoaiSP/Delete.cshtml
@model MobileShopConnection.LoaiSP

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminMainLayout.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Xoá Loại Sản Phẩm
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="@Url.Action("Index","LoaiSP")">Loại Sản Phẩm</a>
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> Xóa Loại Sản Phẩm
                </li>
            </ol>
            <h3>Are you sure you want to delete this?</h3>
            <div>
                <h4>LoaiSP</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Mã Loại
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MaLoai)
                    </dd>

                    <dt>
                        Tên Loại
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenLoai)
                    </dd>

                    <dt>
                       Bị Xóa
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BiXoa)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>

        </div>
    </div>
    <!-- /.row -->
</div>

WebApplication1/Areas/Admin/Views/LoaiSP/Deleted.cshtml
@model PetaPoco.Page<MobileShopConnection.LoaiSP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminMainLayout.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Loại Sản Phẩm Đã Xóa
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="@Url.Action("Index","LoaiSP")">Loại Sản Phẩm</a>
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> Loại Sản Phẩm Đã Xóa
                </li>
            </ol>
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            Mã Loại
                        </th>
                        <th>
                            Tên Loại
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaLoai)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenLoai)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.MaLoai }) |
                                @Html.ActionLink("Restore", "Restore", new { id = item.MaLoai })
                            </td>
                        </tr>
                    }

                </table>
            </div>
            <div class="text-center">
                <ul class="pagination">
                    @{
                        if (Model.CurrentPage > 1)
                        {
                            <li>
                                <a href="@Url.Action("Index","LoaiSP",new { Page = Model.CurrentPage - 1})" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        }
                    }
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        if (i == Model.CurrentPage)
                        {
                            <li class="active">@Html.ActionLink(i.ToString(), "Index", new { Page = i })</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink(i.ToString(), "Index", new { Page = i })</li>
                        }
                    }
                    @{
                        if (Model.CurrentPage < Model.TotalPages)
                        {
                            <li>
                                <a href="@Url.Action("Index","LoaiSP",new { Page = Model.CurrentPage + 1})" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
        <!-- /.row -->
    </div>
</div>

WebApplication1/Areas/Admin/Views/LoaiSP/Edit.cshtml
@model MobileShopConnection.LoaiSP

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminMainLayout.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Sửa Loại Sản Phẩm
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="@Url.Action("Index","LoaiSP")">Loại Sản Phẩm</a>
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> Sửa Loại Sản Phẩm
                </li>
            </ol>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>LoaiSP</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label class="control-label col-md-2">Mã Loại</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MaLoai, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Tên Loại Sản Phẩm</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Bị Xóa</label>
                        <div class="col-md-10">
                            @Html.DropDownList("BiXoa", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.BiXoa, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
    <!-- /.row -->
</div>

WebApplication1/Areas/Admin/Views/LoaiSP/Index.cshtml
@model PetaPoco.Page<MobileShopConnection.LoaiSP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminMainLayout.cshtml";
}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <p>
                @Html.ActionLink("Thêm", "Create")      |       
                @Html.ActionLink("Loại Sản Phẩm Đã Xóa", "Deleted")
            </p>
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            Mã Loại
                        </th>
                        <th>
                            Tên Loại
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaLoai)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenLoai)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.MaLoai }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.MaLoai })
                            </td>
                        </tr>
                    }

                </table>
            </div>
            <div class="text-center">
                <ul class="pagination">
                    @{
                        if (Model.CurrentPage > 1)
                        {
                            <li>
                                <a href="@Url.Action("Index","SanPham",new { Page = Model.CurrentPage - 1})" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        }
                    }
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        if (i == Model.CurrentPage)
                        {
                            <li class="active">@Html.ActionLink(i.ToString(), "Index", new { Page = i })</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink(i.ToString(), "Index", new { Page = i })</li>
                        }
                    }
                    @{
                        if (Model.CurrentPage < Model.TotalPages)
                        {
                            <li>
                                <a href="@Url.Action("Index","SanPham",new { Page = Model.CurrentPage + 1})" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    <!-- /.row -->
    </div>
</div>