WebApplication1/Areas/Admin/Controllers/HangSPController.cs
using MobileShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HangSPController : Controller
    {
        // GET: Admin/HangSP
        public ActionResult Index(int Page = 1)
        {
            var DsHangSP = HangBus.PageDanhSach(Page, 10);
            return View(DsHangSP);
        }

        // GET: Admin/HangSP/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/HangSP/Create
        public ActionResult Create()
        {
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            return View();
        }

        // POST: Admin/HangSP/Create
        [HttpPost]
        public ActionResult Create(HangSP HangSP)
        {
            try
            {
                // TODO: Add insert logic here
                HangBus.Them(HangSP);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/HangSP/Edit/5
        public ActionResult Edit(int id)
        {
            var rs = HangBus.ChiTiet(id);
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            return View(rs);
        }

        // POST: Admin/HangSP/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HangSP HangSP)
        {
            try
            {
                // TODO: Add update logic here
                HangBus.Sua(HangSP);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/HangSP/Delete/5
        public ActionResult Delete(int id)
        {
            var rs = HangBus.ChiTiet(id);
            return View(rs);
        }

        // POST: Admin/HangSP/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                HangBus.Xoa(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Deleted(int Page = 1)
        {
            var DsHangSP = HangBus.PageDanhSachDaXoa(Page,10);
            return View(DsHangSP);
        }
        public ActionResult Restore(int id)
        {
            HangBus.KhoiPhuc(id);
            return RedirectToAction("Deleted");
        }
    }
}

WebApplication1/Areas/Admin/Controllers/LoaiSPController.cs
using MobileShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LoaiSPController : Controller
    {
        
        // GET: Admin/LoaiSP
        public ActionResult Index(int Page = 1)
        {
            var DsLoaiSP = LoaiBus.PageDanhSach(Page,10);
            return View(DsLoaiSP);
        }

        // GET: Admin/LoaiSP/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSP/Create
        public ActionResult Create()
        {
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            return View();
        }

        // POST: Admin/LoaiSP/Create
        [HttpPost]
        public ActionResult Create(LoaiSP LoaiSP)
        {
            try
            {
                // TODO: Add insert logic here
                LoaiBus.Them(LoaiSP);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSP/Edit/5
        public ActionResult Edit(int id)
        {
            var rs = LoaiBus.ChiTiet(id);
            List<CustomDropDownList> BiXoa = new List<CustomDropDownList>()
            {
                new CustomDropDownList {Text="Không Xóa",Value=0 },
                new CustomDropDownList {Text="Xóa",Value=1 }
            };
            ViewBag.BiXoa = new SelectList(BiXoa, "Value", "Text");
            return View(rs);
        }

        // POST: Admin/LoaiSP/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, LoaiSP LoaiSP)
        {
            try
            {
                // TODO: Add update logic here
                LoaiBus.Sua(LoaiSP);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSP/Delete/5
        public ActionResult Delete(int id)
        {
            var rs = LoaiBus.ChiTiet(id);
            return View(rs);
        }

        // POST: Admin/LoaiSP/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                LoaiBus.Xoa(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Deleted(int Page = 1)
        {
            var rs = LoaiBus.PageDanhSachDaXoa(Page,10);
            return View(rs);
        }
        public ActionResult Restore(int id)
        {
            LoaiBus.KhoiPhuc(id);
            return RedirectToAction("Deleted");
        }
    }
}

WebApplication1/Areas/Admin/Views/Shared/_AdminMainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Bootstrap Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Areas/Admin/AdminTemplate/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Areas/Admin/AdminTemplate/css/sb-admin.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Areas/Admin/AdminTemplate/css/plugins/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Areas/Admin/AdminTemplate/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","DashBoard")">Admin Page</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Huỳnh Vinh Phát</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Huỳnh Vinh Phát</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Huỳnh Vinh Phát</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Huỳnh Vinh Phát <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="@Url.Action("Index","DashBoard")"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","SanPham")"><i class="fa fa-fw fa-wrench"></i> Quản Lý Sản Phẩm</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","HangSP")"><i class="fa fa-fw fa-wrench"></i> Quản Lý Hãng</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","LoaiSP")"><i class="fa fa-fw fa-wrench"></i> Quản Lý Loại Sản Phẩm</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
    <div id="page-wrapper">
        @RenderBody()
    </div>
    </div>
    <script src="~/Areas/Admin/AdminTemplate/js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Areas/Admin/AdminTemplate/js/bootstrap.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Areas/Admin/AdminTemplate/js/plugins/morris/raphael.min.js"></script>
    <script src="~/Areas/Admin/AdminTemplate/js/plugins/morris/morris.min.js"></script>
    <script src="~/Areas/Admin/AdminTemplate/js/plugins/morris/morris-data.js"></script>
    <script src="//cdn.ckeditor.com/4.6.2/basic/ckeditor.js"></script>
</body>
</html>